#!/bin/bash

###############################################################################
#	Building General/Programming/dbgmsg libraries and programs
###############################################################################

pushd Library && (./Build || true) && popd

pushd test-dbgmsg && (./Build || true) && popd


